#define TAPPING_TERM 250
#define AUTO_SHIFT_TIMEOUT 135
#define PERMISSIVE_HOLD
// #define LEADER_TIMEOUT 300
#ifdef RGB_MATRIX_ENABLE
    #define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_SOLID_COLOR
    #define RGB_DISABLE_WHEN_USB_SUSPENDED true
#endif
